#!/bin/sh
set -e
masterBranch="master"

((!$#)) && echo No release name, command ignored! && echo "  - git release <version>" && exit 1

if [[ "$1" = "--h" ]] ; then
   echo "Creates a release branch at the latest commit on $masterBranch and checks it out.";
   echo "  - git release <version>";
   exit 1;
fi

if ! [ -d .git ] ; then
	if ! [ $(git rev-parse --is-inside-work-tree &>/dev/null; echo "${?}") == '0' ] ; then
		echo "Current directory is not a git folder."
		exit 1;
	fi
fi

numericRegex="^[.0-9]+$"
if ! [[ "$1" =~ $numericRegex ]] ; then
   echo error: Not a numberic version
   exit 1
fi

echo Starting release $1
git checkout -b release/$1 $masterBranch