#!/bin/sh
set -e
masterBranch="master"

((!$#)) && echo No release name, command ignored! && echo "  - git release <version> <startingPoint>" && exit 1

if [[ "$1" = "--h" ]] ; then
   echo "Creates a release branch at either the latest commit on $masterBranch or when supplied the <startingPoint> and checks it out.";
   echo "  - git release <version> <startingPoint>";
   exit 1;
fi

if ! [ -d .git ] ; then
	if ! [ $(git rev-parse --is-inside-work-tree &>/dev/null; echo "${?}") == '0' ] ; then
		echo "Current directory is not a git folder."
		exit 1;
	fi
fi

numericRegex="^[.0-9]+$"
if ! [[ "$1" =~ $numericRegex ]] ; then
   echo error: Not a numeric version
   exit 1
fi


head=$masterBranch
if [ "$2" = "" ]; then
	echo branching from latest commit on $head
else
	head=$2
	echo branching from requested starting point: $head
fi

echo Starting release $1
git checkout -b release/$1 $head