#!/bin/sh
set -e
masterBranch="master"

((!$#)) && echo No feature name, command ignored! && echo "  - git feature <name>" && exit 1

if [[ "$1" = "--h" ]] ; then
   echo "Creates a feature branch at the latest commit on $masterBranch and checks it out.";
   echo "Feature branches will create a pull request to $masterBranch when finished."
   echo "  - git feature <name>";
   exit 1;
fi

if ! [ -d .git ] ; then
	if ! [ $(git rev-parse --is-inside-work-tree &>/dev/null; echo "${?}") == '0' ] ; then
		echo "Current directory is not a git folder."
		exit 1;
	fi
fi

echo Starting feature $1
git checkout -b feature/$1 $masterBranch